x = input('Olá, digite algo: ')
print('O tipo primitivo dessa variável é',type(x))
print('É alfabético? ',x.isalpha())
print('É numérico? ',x.isnumeric())
print('Só tem espaços? ',x.isspace())
print('É alfanumérico? ',x.isalnum())
print('É minúsculo? ',x.islower())
print('É maiúsculo? ',x.isupper())
print('Está captalizado? ',x.istitle())
